SELECT
    M.CD_PESSOA_FISICA,
    M.NM_GUERRA,
    M.NR_CRM,
    M.UF_CRM,
    P.NR_CPF,
    P.IE_SEXO,
    P.DT_NASCIMENTO,
    P.IE_ESTADO_CIVIL
FROM
    PESSOA_FISICA P,
    MEDICO        M
WHERE
    P.CD_PESSOA_FISICA = M.CD_PESSOA_FISICA