SELECT
    P.CD_PESSOA_FISICA,
    P.NM_PESSOA_FISICA,
    LISTAGG(C.NM_CONTATO, ', ') WITHIN GROUP (ORDER BY C.NM_CONTATO) AS NM_CONTATOS,
    P.NR_CPF,
    P.DT_NASCIMENTO,
    TRUNC((MONTHS_BETWEEN(SYSDATE, P.DT_NASCIMENTO)) / 12)           AS IDADE,
    P.IE_SEXO,
    P.NR_CEP_CIDADE_NASC
FROM
    PESSOA_FISICA       P
    LEFT JOIN COMPL_PESSOA_FISICA C
    ON P.CD_PESSOA_FISICA = C.CD_PESSOA_FISICA
WHERE
    P.NR_CPF IS NOT NULL
GROUP BY
    P.CD_PESSOA_FISICA,
    P.NM_PESSOA_FISICA,
    CEP.DS_UF,
    P.NR_CPF,
    P.DT_NASCIMENTO,
    P.NR_CEP_CIDADE_NASC,
    P.IE_SEXO